[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "goldengoose"
authors = [{name = "Goldengoose Research Team", email = "support@goldengoose.tech"}]
dynamic = ["0.1.0", "Goldengose data python api"]
