#!/usr/bin/env python

import goldengoose
import datetime

stock_data = goldengoose.stocks.get('ADBE')
epoch = goldengoose.get_current_epoch()

while True:
    if epoch not in stock_data:
        goldengoose.wait_till_next_epoch()
    print (stock_data[epoch])
