#!/usr/bin/env python

import goldengoose
import datetime

stock_data = goldengoose.stocks.get('ADBE')

# Get data start time...
start_date = str(stock_data['start'], encoding='ascii')
start_date = datetime.datetime.strptime(start_date, '%Y-%m-%dT%H:%M:%SZ')

while start_date < datetime.datetime.now():
    key = start_date.strftime("%Y-%m-%dT%H:%M:%SZ")
    data = stock_data[key]
    print (key, data)
    start_date += datetime.timedelta(minutes=5)
